### ISSUE TITLE
Many 429 errors

### ISSUE THREAD

**Issue by JordanMakesMaps** [SMillerTime57/coralnet_api_deployer#1]
Thanks for making your code available. I'm running into many 429 response errors which indicates that I'm making too many requests. I see that you currently have your script to ask for 30 points per image, and you only send a single request containing up to, but not more than 100 images. 

How long did it take for all your images to be annotated? Is this something you would run for a few days?... I've set the wait time to 120 seconds instead of 60 but I'm still running into issues.

Any insight you'd be willing to share is appreciated. Cheers.

**Comment by S-D-Miller** [comment]
Hi Jordan,

Thanks for reaching out!  For me, it was usually taking about 7-10 minutes
to annotate a set of 100 images, but there would be times where the server
was busy and it wouldn't progress for a half hour or so.  Typically I was
able to get ~6000 - 10000 images  (basically one of my CoralNet folders)
annotated a day using the coralnet_api_deployer script.  For a job that
size it would run for most of the day and occasionally would still be going
overnight.

In terms of the 429 codes, I'm not sure what could be causing that.  While
I was talking with the developers in the beginning they said the pace at
which these scripts send requests should be within the boundaries of
what they allow.  If you are trying to run multiple instances of the script
with the same authentication token you may be reaching the threshold,
because I believe they limit users to a certain number of concurrent jobs.
I've never run into 429 errors with how it's written, but I've only ever
tried running one instance at a time.

I hope that helps, but if you're running into those 429 error codes
frequently, it may be worth reaching out to the CoralNet developers.  They
may be able to monitor from their end while you send some requests and give
more insight on what the actual cutoffs are and how you are reaching them.

Scott

**Comment by JordanMakesMaps** [comment]
Hey Scott, thanks for your reply, very helpful indeed. I found that 429 responses were to due to too many requests being made, and this was because they currently have it set to do 5 active requests at a time. But I was requesting way too many point annotations and caused out of memory errors which brought my requests to a complete halt. That was why it was taking to long.. But I talked to Oscar and sorted it out and I'll try again. Thanks!
